{
  "min_id": "614161089898524675",
  "max_id": "614461312034189321",
  "events": [
    {
      "id": "614161089898524675",
      "source_ip": "77.230.10.247",
      "program": "nexio_web",
      "message": "Internal Server Error: /reports/generate/ Traceback (most recent call last):   File \"/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py\", line 111, in get_response     response = wrapped_callback(request, *callback_args, **callback_kwargs)   File \"/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py\", line 69, in view     return self.dispatch(request, *args, **kwargs)   File \"/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py\", line 87, in dispatch     return handler(request, *args, **kwargs)   File \"/home/x/Code/Tecnilab/nexioweb/reports/views.py\", line 211, in get     obj = pdf_creator.generate_pdfs(request.GET['toPDF'], request.session['username'], request.session['sessionid'], noncompliance, ids_checks)   File \"/home/x/Code/Tecnilab/nexioweb/utils/pdf_maker_cron/pdf_creator_report.py\", line 151, in generate_pdfs     buff, name = self.generate_pdf(username, session, noncompliance, id_check)   File \"/home/x/Code/Tecnilab/nexioweb/utils/pdf_maker_cron/pdf_creator_report.py\", line 160, in generate_pdf     pdf, name = self.get_pdf(id)   File \"/home/x/Code/Tecnilab/nexioweb/utils/pdf_maker_cron/pdf_creator_report.py\", line 282, in get_pdf     bucket = con.get_bucket('informes.nexio.cat')   File \"/home/x/.local/lib/python2.7/site-packages/boto/s3/connection.py\", line 502, in get_bucket     return self.head_bucket(bucket_name, headers=headers)   File \"/home/x/.local/lib/python2.7/site-packages/boto/s3/connection.py\", line 521, in head_bucket     response = self.make_request('HEAD', bucket_name, headers=headers)   File \"/home/x/.local/lib/python2.7/site-packages/boto/s3/connection.py\", line 664, in make_request     retry_handler=retry_handler   File \"/home/x/.local/lib/python2.7/site-packages/boto/connection.py\", line 1071, in make_request     retry_handler=retry_handler)   File \"/home/x/.local/lib/python2.7/site-packages/boto/connection.py\", line 943, in _mexe     request.body, request.headers)   File \"/usr/lib/python2.7/httplib.py\", line 1052, in request     self._send_request(method, url, body, headers)   File \"/usr/lib/python2.7/httplib.py\", line 1092, in _send_request     self.endheaders(body)   File \"/usr/lib/python2.7/httplib.py\", line 1048, in endheaders     self._send_output(message_body)   File \"/usr/lib/python2.7/httplib.py\", line 892, in _send_output     self.send(msg)   File \"/usr/lib/python2.7/httplib.py\", line 854, in send     self.connect()   File \"/usr/lib/python2.7/httplib.py\", line 1273, in connect     server_hostname=server_hostname)   File \"/usr/lib/python2.7/ssl.py\", line 352, in wrap_socket     _context=self)   File \"/usr/lib/python2.7/ssl.py\", line 579, in __init__     self.do_handshake()   File \"/usr/lib/python2.7/ssl.py\", line 816, in do_handshake     match_hostname(self.getpeercert(), self.server_hostname)   File \"/usr/lib/python2.7/ssl.py\", line 271, in match_hostname     % (hostname, ', '.join(map(repr, dnsnames)))) CertificateError: hostname 'informes.nexio.cat.s3.amazonaws.com' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com' ",
      "received_at": "2015-12-17T16:03:56+01:00",
      "generated_at": "2015-12-17T16:03:56+01:00",
      "display_received_at": "Dec 17 16:03:56",
      "source_id": 111735203,
      "source_name": "localhost_test",
      "hostname": "localhost_test",
      "severity": "Error",
      "facility": "User"
    },
    {
      "id": "614161298628063237",
      "source_ip": "77.230.10.247",
      "program": "nexio_web",
      "message": "Internal Server Error: /reports/generate/ Traceback (most recent call last):   File \"/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py\", line 111, in get_response     response = wrapped_callback(request, *callback_args, **callback_kwargs)   File \"/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py\", line 69, in view     return self.dispatch(request, *args, **kwargs)   File \"/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py\", line 87, in dispatch     return handler(request, *args, **kwargs)   File \"/home/x/Code/Tecnilab/nexioweb/reports/views.py\", line 211, in get     obj = pdf_creator.generate_pdfs(request.GET['toPDF'], request.session['username'], request.session['sessionid'], noncompliance, ids_checks)   File \"/home/x/Code/Tecnilab/nexioweb/utils/pdf_maker_cron/pdf_creator_report.py\", line 151, in generate_pdfs     buff, name = self.generate_pdf(username, session, noncompliance, id_check)   File \"/home/x/Code/Tecnilab/nexioweb/utils/pdf_maker_cron/pdf_creator_report.py\", line 160, in generate_pdf     pdf, name = self.get_pdf(id)   File \"/home/x/Code/Tecnilab/nexioweb/utils/pdf_maker_cron/pdf_creator_report.py\", line 282, in get_pdf     bucket = con.get_bucket('informes.nexio.cat')   File \"/home/x/.local/lib/python2.7/site-packages/boto/s3/connection.py\", line 502, in get_bucket     return self.head_bucket(bucket_name, headers=headers)   File \"/home/x/.local/lib/python2.7/site-packages/boto/s3/connection.py\", line 521, in head_bucket     response = self.make_request('HEAD', bucket_name, headers=headers)   File \"/home/x/.local/lib/python2.7/site-packages/boto/s3/connection.py\", line 664, in make_request     retry_handler=retry_handler   File \"/home/x/.local/lib/python2.7/site-packages/boto/connection.py\", line 1071, in make_request     retry_handler=retry_handler)   File \"/home/x/.local/lib/python2.7/site-packages/boto/connection.py\", line 943, in _mexe     request.body, request.headers)   File \"/usr/lib/python2.7/httplib.py\", line 1052, in request     self._send_request(method, url, body, headers)   File \"/usr/lib/python2.7/httplib.py\", line 1092, in _send_request     self.endheaders(body)   File \"/usr/lib/python2.7/httplib.py\", line 1048, in endheaders     self._send_output(message_body)   File \"/usr/lib/python2.7/httplib.py\", line 892, in _send_output     self.send(msg)   File \"/usr/lib/python2.7/httplib.py\", line 854, in send     self.connect()   File \"/usr/lib/python2.7/httplib.py\", line 1273, in connect     server_hostname=server_hostname)   File \"/usr/lib/python2.7/ssl.py\", line 352, in wrap_socket     _context=self)   File \"/usr/lib/python2.7/ssl.py\", line 579, in __init__     self.do_handshake()   File \"/usr/lib/python2.7/ssl.py\", line 816, in do_handshake     match_hostname(self.getpeercert(), self.server_hostname)   File \"/usr/lib/python2.7/ssl.py\", line 271, in match_hostname     % (hostname, ', '.join(map(repr, dnsnames)))) CertificateError: hostname 'informes.nexio.cat.s3.amazonaws.com' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com' ",
      "received_at": "2015-12-17T16:04:46+01:00",
      "generated_at": "2015-12-17T16:04:46+01:00",
      "display_received_at": "Dec 17 16:04:46",
      "source_id": 111735203,
      "source_name": "localhost_test",
      "hostname": "localhost_test",
      "severity": "Error",
      "facility": "User"
    },
    {
      "id": "614161380622512149",
      "source_ip": "77.230.10.247",
      "program": "nexio_web",
      "message": "Internal Server Error: /reports/generate/ Traceback (most recent call last):   File \"/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py\", line 111, in get_response     response = wrapped_callback(request, *callback_args, **callback_kwargs)   File \"/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py\", line 69, in view     return self.dispatch(request, *args, **kwargs)   File \"/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py\", line 87, in dispatch     return handler(request, *args, **kwargs)   File \"/home/x/Code/Tecnilab/nexioweb/reports/views.py\", line 211, in get     obj = pdf_creator.generate_pdfs(request.GET['toPDF'], request.session['username'], request.session['sessionid'], noncompliance, ids_checks)   File \"/home/x/Code/Tecnilab/nexioweb/utils/pdf_maker_cron/pdf_creator_report.py\", line 151, in generate_pdfs     buff, name = self.generate_pdf(username, session, noncompliance, id_check)   File \"/home/x/Code/Tecnilab/nexioweb/utils/pdf_maker_cron/pdf_creator_report.py\", line 160, in generate_pdf     pdf, name = self.get_pdf(id)   File \"/home/x/Code/Tecnilab/nexioweb/utils/pdf_maker_cron/pdf_creator_report.py\", line 282, in get_pdf     bucket = con.get_bucket('informes.nexio.cat')   File \"/home/x/.local/lib/python2.7/site-packages/boto/s3/connection.py\", line 502, in get_bucket     return self.head_bucket(bucket_name, headers=headers)   File \"/home/x/.local/lib/python2.7/site-packages/boto/s3/connection.py\", line 521, in head_bucket     response = self.make_request('HEAD', bucket_name, headers=headers)   File \"/home/x/.local/lib/python2.7/site-packages/boto/s3/connection.py\", line 664, in make_request     retry_handler=retry_handler   File \"/home/x/.local/lib/python2.7/site-packages/boto/connection.py\", line 1071, in make_request     retry_handler=retry_handler)   File \"/home/x/.local/lib/python2.7/site-packages/boto/connection.py\", line 943, in _mexe     request.body, request.headers)   File \"/usr/lib/python2.7/httplib.py\", line 1052, in request     self._send_request(method, url, body, headers)   File \"/usr/lib/python2.7/httplib.py\", line 1092, in _send_request     self.endheaders(body)   File \"/usr/lib/python2.7/httplib.py\", line 1048, in endheaders     self._send_output(message_body)   File \"/usr/lib/python2.7/httplib.py\", line 892, in _send_output     self.send(msg)   File \"/usr/lib/python2.7/httplib.py\", line 854, in send     self.connect()   File \"/usr/lib/python2.7/httplib.py\", line 1273, in connect     server_hostname=server_hostname)   File \"/usr/lib/python2.7/ssl.py\", line 352, in wrap_socket     _context=self)   File \"/usr/lib/python2.7/ssl.py\", line 579, in __init__     self.do_handshake()   File \"/usr/lib/python2.7/ssl.py\", line 816, in do_handshake     match_hostname(self.getpeercert(), self.server_hostname)   File \"/usr/lib/python2.7/ssl.py\", line 271, in match_hostname     % (hostname, ', '.join(map(repr, dnsnames)))) CertificateError: hostname 'informes.nexio.cat.s3.amazonaws.com' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com' ",
      "received_at": "2015-12-17T16:05:06+01:00",
      "generated_at": "2015-12-17T16:05:06+01:00",
      "display_received_at": "Dec 17 16:05:06",
      "source_id": 111735203,
      "source_name": "localhost_test",
      "hostname": "localhost_test",
      "severity": "Error",
      "facility": "User"
    },
    {
      "id": "614161711972528176",
      "source_ip": "77.230.10.247",
      "program": "nexio_web",
      "message": "Internal Server Error: /reports/generate/ Traceback (most recent call last):   File \"/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py\", line 111, in get_response     response = wrapped_callback(request, *callback_args, **callback_kwargs)   File \"/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py\", line 69, in view     return self.dispatch(request, *args, **kwargs)   File \"/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py\", line 87, in dispatch     return handler(request, *args, **kwargs)   File \"/home/x/Code/Tecnilab/nexioweb/reports/views.py\", line 211, in get     obj = pdf_creator.generate_pdfs(request.GET['toPDF'], request.session['username'], request.session['sessionid'], noncompliance, ids_checks)   File \"/home/x/Code/Tecnilab/nexioweb/utils/pdf_maker_cron/pdf_creator_report.py\", line 151, in generate_pdfs     buff, name = self.generate_pdf(username, session, noncompliance, id_check)   File \"/home/x/Code/Tecnilab/nexioweb/utils/pdf_maker_cron/pdf_creator_report.py\", line 160, in generate_pdf     pdf, name = self.get_pdf(id)   File \"/home/x/Code/Tecnilab/nexioweb/utils/pdf_maker_cron/pdf_creator_report.py\", line 282, in get_pdf     bucket = con.get_bucket('informes.nexio.cat')   File \"/home/x/.local/lib/python2.7/site-packages/boto/s3/connection.py\", line 502, in get_bucket     return self.head_bucket(bucket_name, headers=headers)   File \"/home/x/.local/lib/python2.7/site-packages/boto/s3/connection.py\", line 521, in head_bucket     response = self.make_request('HEAD', bucket_name, headers=headers)   File \"/home/x/.local/lib/python2.7/site-packages/boto/s3/connection.py\", line 664, in make_request     retry_handler=retry_handler   File \"/home/x/.local/lib/python2.7/site-packages/boto/connection.py\", line 1071, in make_request     retry_handler=retry_handler)   File \"/home/x/.local/lib/python2.7/site-packages/boto/connection.py\", line 943, in _mexe     request.body, request.headers)   File \"/usr/lib/python2.7/httplib.py\", line 1052, in request     self._send_request(method, url, body, headers)   File \"/usr/lib/python2.7/httplib.py\", line 1092, in _send_request     self.endheaders(body)   File \"/usr/lib/python2.7/httplib.py\", line 1048, in endheaders     self._send_output(message_body)   File \"/usr/lib/python2.7/httplib.py\", line 892, in _send_output     self.send(msg)   File \"/usr/lib/python2.7/httplib.py\", line 854, in send     self.connect()   File \"/usr/lib/python2.7/httplib.py\", line 1273, in connect     server_hostname=server_hostname)   File \"/usr/lib/python2.7/ssl.py\", line 352, in wrap_socket     _context=self)   File \"/usr/lib/python2.7/ssl.py\", line 579, in __init__     self.do_handshake()   File \"/usr/lib/python2.7/ssl.py\", line 816, in do_handshake     match_hostname(self.getpeercert(), self.server_hostname)   File \"/usr/lib/python2.7/ssl.py\", line 271, in match_hostname     % (hostname, ', '.join(map(repr, dnsnames)))) CertificateError: hostname 'informes.nexio.cat.s3.amazonaws.com' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com' ",
      "received_at": "2015-12-17T16:06:25+01:00",
      "generated_at": "2015-12-17T16:06:25+01:00",
      "display_received_at": "Dec 17 16:06:25",
      "source_id": 111735203,
      "source_name": "localhost_test",
      "hostname": "localhost_test",
      "severity": "Error",
      "facility": "User"
    },
    {
      "id": "614161727218823189",
      "source_ip": "77.230.10.247",
      "program": "nexio_web",
      "message": "Internal Server Error: /reports/generate/ Traceback (most recent call last):   File \"/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py\", line 111, in get_response     response = wrapped_callback(request, *callback_args, **callback_kwargs)   File \"/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py\", line 69, in view     return self.dispatch(request, *args, **kwargs)   File \"/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py\", line 87, in dispatch     return handler(request, *args, **kwargs)   File \"/home/x/Code/Tecnilab/nexioweb/reports/views.py\", line 211, in get     obj = pdf_creator.generate_pdfs(request.GET['toPDF'], request.session['username'], request.session['sessionid'], noncompliance, ids_checks)   File \"/home/x/Code/Tecnilab/nexioweb/utils/pdf_maker_cron/pdf_creator_report.py\", line 151, in generate_pdfs     buff, name = self.generate_pdf(username, session, noncompliance, id_check)   File \"/home/x/Code/Tecnilab/nexioweb/utils/pdf_maker_cron/pdf_creator_report.py\", line 160, in generate_pdf     pdf, name = self.get_pdf(id)   File \"/home/x/Code/Tecnilab/nexioweb/utils/pdf_maker_cron/pdf_creator_report.py\", line 282, in get_pdf     bucket = con.get_bucket('informes.nexio.cat')   File \"/home/x/.local/lib/python2.7/site-packages/boto/s3/connection.py\", line 502, in get_bucket     return self.head_bucket(bucket_name, headers=headers)   File \"/home/x/.local/lib/python2.7/site-packages/boto/s3/connection.py\", line 521, in head_bucket     response = self.make_request('HEAD', bucket_name, headers=headers)   File \"/home/x/.local/lib/python2.7/site-packages/boto/s3/connection.py\", line 664, in make_request     retry_handler=retry_handler   File \"/home/x/.local/lib/python2.7/site-packages/boto/connection.py\", line 1071, in make_request     retry_handler=retry_handler)   File \"/home/x/.local/lib/python2.7/site-packages/boto/connection.py\", line 943, in _mexe     request.body, request.headers)   File \"/usr/lib/python2.7/httplib.py\", line 1052, in request     self._send_request(method, url, body, headers)   File \"/usr/lib/python2.7/httplib.py\", line 1092, in _send_request     self.endheaders(body)   File \"/usr/lib/python2.7/httplib.py\", line 1048, in endheaders     self._send_output(message_body)   File \"/usr/lib/python2.7/httplib.py\", line 892, in _send_output     self.send(msg)   File \"/usr/lib/python2.7/httplib.py\", line 854, in send     self.connect()   File \"/usr/lib/python2.7/httplib.py\", line 1273, in connect     server_hostname=server_hostname)   File \"/usr/lib/python2.7/ssl.py\", line 352, in wrap_socket     _context=self)   File \"/usr/lib/python2.7/ssl.py\", line 579, in __init__     self.do_handshake()   File \"/usr/lib/python2.7/ssl.py\", line 816, in do_handshake     match_hostname(self.getpeercert(), self.server_hostname)   File \"/usr/lib/python2.7/ssl.py\", line 271, in match_hostname     % (hostname, ', '.join(map(repr, dnsnames)))) CertificateError: hostname 'informes.nexio.cat.s3.amazonaws.com' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com' ",
      "received_at": "2015-12-17T16:06:28+01:00",
      "generated_at": "2015-12-17T16:06:28+01:00",
      "display_received_at": "Dec 17 16:06:28",
      "source_id": 111735203,
      "source_name": "localhost_test",
      "hostname": "localhost_test",
      "severity": "Error",
      "facility": "User"
    },
    {
      "id": "614167134578454534",
      "source_ip": "82.98.176.85",
      "program": "apache-error",
      "message": "[Wed Dec 16 15:49:40 2015] [error] Not Found: /information/",
      "received_at": "2015-12-17T16:27:58+01:00",
      "generated_at": "2015-12-16T16:49:40+01:00",
      "display_received_at": "Dec 17 16:27:58",
      "source_id": 91453434,
      "source_name": "vls15613",
      "hostname": "vls15613",
      "severity": "Notice",
      "facility": "Local1"
    },
    {
      "id": "614167134578454539",
      "source_ip": "82.98.176.85",
      "program": "apache-error",
      "message": "[Wed Dec 16 15:49:40 2015] [error] django.request : MainThread > Not Found: /information/",
      "received_at": "2015-12-17T16:27:58+01:00",
      "generated_at": "2015-12-16T16:49:40+01:00",
      "display_received_at": "Dec 17 16:27:58",
      "source_id": 91453434,
      "source_name": "vls15613",
      "hostname": "vls15613",
      "severity": "Notice",
      "facility": "Local1"
    },
    {
      "id": "614167134586843146",
      "source_ip": "82.98.176.85",
      "program": "apache",
      "message": "77.230.10.247 - - [16/Dec/2015:15:49:40 +0000] \"GET /information/ HTTP/1.1\" 404 3713",
      "received_at": "2015-12-17T16:27:58+01:00",
      "generated_at": "2015-12-16T16:49:40+01:00",
      "display_received_at": "Dec 17 16:27:58",
      "source_id": 91453434,
      "source_name": "vls15613",
      "hostname": "vls15613",
      "severity": "Notice",
      "facility": "Local1"
    },
    {
      "id": "614167140848939025",
      "source_ip": "82.98.176.85",
      "program": "apache",
      "message": "77.230.10.247 - - [16/Dec/2015:16:04:49 +0000] \"GET /index.php?owa_do=base.loginForm HTTP/1.1\" 404 3727",
      "received_at": "2015-12-17T16:27:59+01:00",
      "generated_at": "2015-12-16T17:04:49+01:00",
      "display_received_at": "Dec 17 16:27:59",
      "source_id": 91453434,
      "source_name": "vls15613",
      "hostname": "vls15613",
      "severity": "Notice",
      "facility": "Local1"
    },
    {
      "id": "614167140848939033",
      "source_ip": "82.98.176.85",
      "program": "apache",
      "message": "77.230.10.247 - - [16/Dec/2015:16:04:49 +0000] \"GET /scripts/index.php?owa_do=base.loginForm HTTP/1.1\" 404 3751",
      "received_at": "2015-12-17T16:27:59+01:00",
      "generated_at": "2015-12-16T17:04:49+01:00",
      "display_received_at": "Dec 17 16:27:59",
      "source_id": 91453434,
      "source_name": "vls15613",
      "hostname": "vls15613",
      "severity": "Notice",
      "facility": "Local1"
    },
    {
      "id": "614167140848939037",
      "source_ip": "82.98.176.85",
      "program": "apache",
      "message": "77.230.10.247 - - [16/Dec/2015:16:04:49 +0000] \"GET /cgi-bin/index.php?owa_do=base.loginForm HTTP/1.1\" 404 3751",
      "received_at": "2015-12-17T16:27:59+01:00",
      "generated_at": "2015-12-16T17:04:49+01:00",
      "display_received_at": "Dec 17 16:27:59",
      "source_id": 91453434,
      "source_name": "vls15613",
      "hostname": "vls15613",
      "severity": "Notice",
      "facility": "Local1"
    },
    {
      "id": "614167140848939041",
      "source_ip": "82.98.176.85",
      "program": "apache",
      "message": "77.230.10.247 - - [16/Dec/2015:16:04:49 +0000] \"GET /index.php?owa_do=base.loginForm HTTP/1.1\" 404 3727",
      "received_at": "2015-12-17T16:27:59+01:00",
      "generated_at": "2015-12-16T17:04:49+01:00",
      "display_received_at": "Dec 17 16:27:59",
      "source_id": 91453434,
      "source_name": "vls15613",
      "hostname": "vls15613",
      "severity": "Notice",
      "facility": "Local1"
    },
    {
      "id": "614167140861521948",
      "source_ip": "82.98.176.85",
      "program": "apache-error",
      "message": "[Wed Dec 16 16:04:51 2015] [error] Not Found: /console/login/LoginForm.jsp",
      "received_at": "2015-12-17T16:27:59+01:00",
      "generated_at": "2015-12-16T17:04:51+01:00",
      "display_received_at": "Dec 17 16:27:59",
      "source_id": 91453434,
      "source_name": "vls15613",
      "hostname": "vls15613",
      "severity": "Notice",
      "facility": "Local1"
    },
    {
      "id": "614167140861521951",
      "source_ip": "82.98.176.85",
      "program": "apache-error",
      "message": "[Wed Dec 16 16:04:51 2015] [error] django.request : Dummy-9    > Not Found: /console/login/LoginForm.jsp",
      "received_at": "2015-12-17T16:27:59+01:00",
      "generated_at": "2015-12-16T17:04:51+01:00",
      "display_received_at": "Dec 17 16:27:59",
      "source_id": 91453434,
      "source_name": "vls15613",
      "hostname": "vls15613",
      "severity": "Notice",
      "facility": "Local1"
    },
    {
      "id": "614167140861521953",
      "source_ip": "82.98.176.85",
      "program": "apache",
      "message": "77.230.10.247 - - [16/Dec/2015:16:04:51 +0000] \"GET /console/login/LoginForm.jsp HTTP/1.1\" 404 3722",
      "received_at": "2015-12-17T16:27:59+01:00",
      "generated_at": "2015-12-16T17:04:51+01:00",
      "display_received_at": "Dec 17 16:27:59",
      "source_id": 91453434,
      "source_name": "vls15613",
      "hostname": "vls15613",
      "severity": "Notice",
      "facility": "Local1"
    },
    {
      "id": "614170151365160982",
      "source_ip": "82.98.176.85",
      "program": "kernel",
      "message": "[27732756.317869] EDD information not available.",
      "received_at": "2015-12-17T16:39:57+01:00",
      "generated_at": "2015-12-17T16:42:48+01:00",
      "display_received_at": "Dec 17 16:39:57",
      "source_id": 91453434,
      "source_name": "vls15613",
      "hostname": "vls15613",
      "severity": "Info",
      "facility": "Kernel"
    },
    {
      "id": "614172370370080770",
      "source_ip": "82.98.176.85",
      "program": "kernel",
      "message": "[27733263.349670] EDD information not available.",
      "received_at": "2015-12-17T16:48:46+01:00",
      "generated_at": "2015-12-17T16:48:43+01:00",
      "display_received_at": "Dec 17 16:48:46",
      "source_id": 91453434,
      "source_name": "vls15613",
      "hostname": "vls15613",
      "severity": "Info",
      "facility": "Kernel"
    },
    {
      "id": "614181040403296306",
      "source_ip": "82.98.176.85",
      "program": "apache-error",
      "message": "[Thu Dec 17 16:23:13 2015] [error] [SERVER_RESULT] Server method returned: [{u'change_date': u'2015-12-07T14:01:16', u'data': u'Informe: 1345', u'from': {u'fullName': u'Sistema Nexio', u'role': u'Sistema', u'name': u'Sistema'}, u'change_number': u'1', u'new_state': u'Oberta'}]",
      "received_at": "2015-12-17T17:23:13+01:00",
      "generated_at": "2015-12-17T17:23:13+01:00",
      "display_received_at": "Dec 17 17:23:13",
      "source_id": 91453434,
      "source_name": "vls15613",
      "hostname": "vls15613",
      "severity": "Notice",
      "facility": "Local1"
    },
    {
      "id": "614182406915928089",
      "source_ip": "82.98.176.85",
      "program": "apache-error",
      "message": "[Thu Dec 17 16:28:39 2015] [error] [SERVER_RESULT] Server method returned: [{u'change_date': u'2015-12-07T14:01:16', u'data': u'Informe: 1345', u'from': {u'fullName': u'Sistema Nexio', u'role': u'Sistema', u'name': u'Sistema'}, u'change_number': u'1', u'new_state': u'Oberta'}]",
      "received_at": "2015-12-17T17:28:39+01:00",
      "generated_at": "2015-12-17T17:28:39+01:00",
      "display_received_at": "Dec 17 17:28:39",
      "source_id": 91453434,
      "source_name": "vls15613",
      "hostname": "vls15613",
      "severity": "Notice",
      "facility": "Local1"
    },
    {
      "id": "614182420329312268",
      "source_ip": "82.98.176.85",
      "program": "apache-error",
      "message": "[Thu Dec 17 16:28:42 2015] [error] [SERVER_RESULT] Server method returned: [{u'change_date': u'2015-12-07T14:01:16', u'data': u'Informe: 1345', u'from': {u'fullName': u'Sistema Nexio', u'role': u'Sistema', u'name': u'Sistema'}, u'change_number': u'1', u'new_state': u'Oberta'}]",
      "received_at": "2015-12-17T17:28:42+01:00",
      "generated_at": "2015-12-17T17:28:42+01:00",
      "display_received_at": "Dec 17 17:28:42",
      "source_id": 91453434,
      "source_name": "vls15613",
      "hostname": "vls15613",
      "severity": "Notice",
      "facility": "Local1"
    },
    {
      "id": "614182438914273288",
      "source_ip": "82.98.176.85",
      "program": "apache-error",
      "message": "[Thu Dec 17 16:28:46 2015] [error] [SERVER_RESULT] Server method returned: [{u'change_date': u'2015-12-07T14:01:16', u'data': u'Informe: 1345', u'from': {u'fullName': u'Sistema Nexio', u'role': u'Sistema', u'name': u'Sistema'}, u'change_number': u'1', u'new_state': u'Oberta'}]",
      "received_at": "2015-12-17T17:28:46+01:00",
      "generated_at": "2015-12-17T17:28:46+01:00",
      "display_received_at": "Dec 17 17:28:46",
      "source_id": 91453434,
      "source_name": "vls15613",
      "hostname": "vls15613",
      "severity": "Notice",
      "facility": "Local1"
    },
    {
      "id": "614182526080299009",
      "source_ip": "82.98.176.85",
      "program": "apache-error",
      "message": "[Thu Dec 17 16:29:07 2015] [error] [SERVER_RESULT] Server method returned: [{u'change_date': u'2015-12-07T14:01:16', u'data': u'Informe: 1345', u'from': {u'fullName': u'Sistema Nexio', u'role': u'Sistema', u'name': u'Sistema'}, u'change_number': u'1', u'new_state': u'Oberta'}]",
      "received_at": "2015-12-17T17:29:07+01:00",
      "generated_at": "2015-12-17T17:29:07+01:00",
      "display_received_at": "Dec 17 17:29:07",
      "source_id": 91453434,
      "source_name": "vls15613",
      "hostname": "vls15613",
      "severity": "Notice",
      "facility": "Local1"
    },
    {
      "id": "614441071866589205",
      "source_ip": "77.230.10.247",
      "program": "nexio_web",
      "message": "Internal Server Error: /reports/generate/ Traceback (most recent call last):   File \"/Library/Python/2.7/site-packages/django/core/handlers/base.py\", line 111, in get_response     response = wrapped_callback(request, *callback_args, **callback_kwargs)   File \"/Library/Python/2.7/site-packages/django/views/generic/base.py\", line 69, in view     return self.dispatch(request, *args, **kwargs)   File \"/Library/Python/2.7/site-packages/django/views/generic/base.py\", line 87, in dispatch     return handler(request, *args, **kwargs)   File \"/Users/IvanSoriano/PycharmProjects/nexioweb/reports/views.py\", line 222, in get     obj = pdf_creator.generate_pdfs(request.GET['toPDF'], request.session['username'], request.session['sessionid'], noncompliance, omit_amazon, ids_checks)   File \"/Users/IvanSoriano/PycharmProjects/nexioweb/utils/pdf_maker_cron/pdf_creator_report.py\", line 166, in generate_pdfs     buff, name = self.generate_pdf(username, session, noncompliance, omit_amazon, id_check)   File \"/Users/IvanSoriano/PycharmProjects/nexioweb/utils/pdf_maker_cron/pdf_creator_report.py\", line 176, in generate_pdf     pdf, name = self.get_pdf(id)   File \"/Users/IvanSoriano/PycharmProjects/nexioweb/utils/pdf_maker_cron/pdf_creator_report.py\", line 313, in get_pdf     bucket = con.get_bucket('informes.nexio.cat')   File \"/Library/Python/2.7/site-packages/boto/s3/connection.py\", line 502, in get_bucket     return self.head_bucket(bucket_name, headers=headers)   File \"/Library/Python/2.7/site-packages/boto/s3/connection.py\", line 521, in head_bucket     response = self.make_request('HEAD', bucket_name, headers=headers)   File \"/Library/Python/2.7/site-packages/boto/s3/connection.py\", line 664, in make_request     retry_handler=retry_handler   File \"/Library/Python/2.7/site-packages/boto/connection.py\", line 1071, in make_request     retry_handler=retry_handler)   File \"/Library/Python/2.7/site-packages/boto/connection.py\", line 943, in _mexe     request.body, request.headers)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 1053, in request     self._send_request(method, url, body, headers)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 1093, in _send_request     self.endheaders(body)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 1049, in endheaders     self._send_output(message_body)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 893, in _send_output     self.send(msg)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 855, in send     self.connect()   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 1274, in connect     server_hostname=server_hostname)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py\", line 352, in wrap_socket     _context=self)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py\", line 579, in __init__     self.do_handshake()   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py\", line 816, in do_handshake     match_hostname(self.getpeercert(), self.server_hostname)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py\", line 271, in match_hostname     % (hostname, ', '.join(map(repr, dnsnames)))) CertificateError: hostname 'informes.nexio.cat.s3.amazonaws.com' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com' ",
      "received_at": "2015-12-18T10:36:29+01:00",
      "generated_at": "2015-12-18T10:36:31+01:00",
      "display_received_at": "Dec 18 10:36:29",
      "source_id": 111735203,
      "source_name": "localhost_test",
      "hostname": "localhost_test",
      "severity": "Error",
      "facility": "User"
    },
    {
      "id": "614441527544164358",
      "source_ip": "77.230.10.247",
      "program": "nexio_web",
      "message": "Internal Server Error: /reports/generate/ Traceback (most recent call last):   File \"/Library/Python/2.7/site-packages/django/core/handlers/base.py\", line 111, in get_response     response = wrapped_callback(request, *callback_args, **callback_kwargs)   File \"/Library/Python/2.7/site-packages/django/views/generic/base.py\", line 69, in view     return self.dispatch(request, *args, **kwargs)   File \"/Library/Python/2.7/site-packages/django/views/generic/base.py\", line 87, in dispatch     return handler(request, *args, **kwargs)   File \"/Users/IvanSoriano/PycharmProjects/nexioweb/reports/views.py\", line 222, in get     obj = pdf_creator.generate_pdfs(request.GET['toPDF'], request.session['username'], request.session['sessionid'], noncompliance, omit_amazon, ids_checks)   File \"/Users/IvanSoriano/PycharmProjects/nexioweb/utils/pdf_maker_cron/pdf_creator_report.py\", line 166, in generate_pdfs     buff, name = self.generate_pdf(username, session, noncompliance, omit_amazon, id_check)   File \"/Users/IvanSoriano/PycharmProjects/nexioweb/utils/pdf_maker_cron/pdf_creator_report.py\", line 176, in generate_pdf     pdf, name = self.get_pdf(id)   File \"/Users/IvanSoriano/PycharmProjects/nexioweb/utils/pdf_maker_cron/pdf_creator_report.py\", line 313, in get_pdf     bucket = con.get_bucket('informes.nexio.cat')   File \"/Library/Python/2.7/site-packages/boto/s3/connection.py\", line 502, in get_bucket     return self.head_bucket(bucket_name, headers=headers)   File \"/Library/Python/2.7/site-packages/boto/s3/connection.py\", line 521, in head_bucket     response = self.make_request('HEAD', bucket_name, headers=headers)   File \"/Library/Python/2.7/site-packages/boto/s3/connection.py\", line 664, in make_request     retry_handler=retry_handler   File \"/Library/Python/2.7/site-packages/boto/connection.py\", line 1071, in make_request     retry_handler=retry_handler)   File \"/Library/Python/2.7/site-packages/boto/connection.py\", line 943, in _mexe     request.body, request.headers)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 1053, in request     self._send_request(method, url, body, headers)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 1093, in _send_request     self.endheaders(body)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 1049, in endheaders     self._send_output(message_body)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 893, in _send_output     self.send(msg)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 855, in send     self.connect()   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 1274, in connect     server_hostname=server_hostname)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py\", line 352, in wrap_socket     _context=self)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py\", line 579, in __init__     self.do_handshake()   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py\", line 816, in do_handshake     match_hostname(self.getpeercert(), self.server_hostname)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py\", line 271, in match_hostname     % (hostname, ', '.join(map(repr, dnsnames)))) CertificateError: hostname 'informes.nexio.cat.s3.amazonaws.com' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com' ",
      "received_at": "2015-12-18T10:38:18+01:00",
      "generated_at": "2015-12-18T10:38:20+01:00",
      "display_received_at": "Dec 18 10:38:18",
      "source_id": 111735203,
      "source_name": "localhost_test",
      "hostname": "localhost_test",
      "severity": "Error",
      "facility": "User"
    },
    {
      "id": "614441786760540173",
      "source_ip": "77.230.10.247",
      "program": "nexio_web",
      "message": "Internal Server Error: /reports/generate/ Traceback (most recent call last):   File \"/Library/Python/2.7/site-packages/django/core/handlers/base.py\", line 111, in get_response     response = wrapped_callback(request, *callback_args, **callback_kwargs)   File \"/Library/Python/2.7/site-packages/django/views/generic/base.py\", line 69, in view     return self.dispatch(request, *args, **kwargs)   File \"/Library/Python/2.7/site-packages/django/views/generic/base.py\", line 87, in dispatch     return handler(request, *args, **kwargs)   File \"/Users/IvanSoriano/PycharmProjects/nexioweb/reports/views.py\", line 222, in get     obj = pdf_creator.generate_pdfs(request.GET['toPDF'], request.session['username'], request.session['sessionid'], noncompliance, omit_amazon, ids_checks)   File \"/Users/IvanSoriano/PycharmProjects/nexioweb/utils/pdf_maker_cron/pdf_creator_report.py\", line 166, in generate_pdfs     buff, name = self.generate_pdf(username, session, noncompliance, omit_amazon, id_check)   File \"/Users/IvanSoriano/PycharmProjects/nexioweb/utils/pdf_maker_cron/pdf_creator_report.py\", line 176, in generate_pdf     pdf, name = self.get_pdf(id)   File \"/Users/IvanSoriano/PycharmProjects/nexioweb/utils/pdf_maker_cron/pdf_creator_report.py\", line 313, in get_pdf     bucket = con.get_bucket('informes.nexio.cat')   File \"/Library/Python/2.7/site-packages/boto/s3/connection.py\", line 502, in get_bucket     return self.head_bucket(bucket_name, headers=headers)   File \"/Library/Python/2.7/site-packages/boto/s3/connection.py\", line 521, in head_bucket     response = self.make_request('HEAD', bucket_name, headers=headers)   File \"/Library/Python/2.7/site-packages/boto/s3/connection.py\", line 664, in make_request     retry_handler=retry_handler   File \"/Library/Python/2.7/site-packages/boto/connection.py\", line 1071, in make_request     retry_handler=retry_handler)   File \"/Library/Python/2.7/site-packages/boto/connection.py\", line 943, in _mexe     request.body, request.headers)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 1053, in request     self._send_request(method, url, body, headers)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 1093, in _send_request     self.endheaders(body)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 1049, in endheaders     self._send_output(message_body)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 893, in _send_output     self.send(msg)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 855, in send     self.connect()   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 1274, in connect     server_hostname=server_hostname)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py\", line 352, in wrap_socket     _context=self)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py\", line 579, in __init__     self.do_handshake()   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py\", line 816, in do_handshake     match_hostname(self.getpeercert(), self.server_hostname)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py\", line 271, in match_hostname     % (hostname, ', '.join(map(repr, dnsnames)))) CertificateError: hostname 'informes.nexio.cat.s3.amazonaws.com' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com' ",
      "received_at": "2015-12-18T10:39:20+01:00",
      "generated_at": "2015-12-18T10:39:21+01:00",
      "display_received_at": "Dec 18 10:39:20",
      "source_id": 111735203,
      "source_name": "localhost_test",
      "hostname": "localhost_test",
      "severity": "Error",
      "facility": "User"
    },
    {
      "id": "614442231927189510",
      "source_ip": "77.230.10.247",
      "program": "nexio_web",
      "message": "Internal Server Error: /reports/generate/ Traceback (most recent call last):   File \"/Library/Python/2.7/site-packages/django/core/handlers/base.py\", line 111, in get_response     response = wrapped_callback(request, *callback_args, **callback_kwargs)   File \"/Library/Python/2.7/site-packages/django/views/generic/base.py\", line 69, in view     return self.dispatch(request, *args, **kwargs)   File \"/Library/Python/2.7/site-packages/django/views/generic/base.py\", line 87, in dispatch     return handler(request, *args, **kwargs)   File \"/Users/IvanSoriano/PycharmProjects/nexioweb/reports/views.py\", line 222, in get     obj = pdf_creator.generate_pdfs(request.GET['toPDF'], request.session['username'], request.session['sessionid'], noncompliance, omit_amazon, ids_checks)   File \"/Users/IvanSoriano/PycharmProjects/nexioweb/utils/pdf_maker_cron/pdf_creator_report.py\", line 166, in generate_pdfs     buff, name = self.generate_pdf(username, session, noncompliance, omit_amazon, id_check)   File \"/Users/IvanSoriano/PycharmProjects/nexioweb/utils/pdf_maker_cron/pdf_creator_report.py\", line 176, in generate_pdf     pdf, name = self.get_pdf(id)   File \"/Users/IvanSoriano/PycharmProjects/nexioweb/utils/pdf_maker_cron/pdf_creator_report.py\", line 313, in get_pdf     bucket = con.get_bucket('informes.nexio.cat')   File \"/Library/Python/2.7/site-packages/boto/s3/connection.py\", line 502, in get_bucket     return self.head_bucket(bucket_name, headers=headers)   File \"/Library/Python/2.7/site-packages/boto/s3/connection.py\", line 521, in head_bucket     response = self.make_request('HEAD', bucket_name, headers=headers)   File \"/Library/Python/2.7/site-packages/boto/s3/connection.py\", line 664, in make_request     retry_handler=retry_handler   File \"/Library/Python/2.7/site-packages/boto/connection.py\", line 1071, in make_request     retry_handler=retry_handler)   File \"/Library/Python/2.7/site-packages/boto/connection.py\", line 943, in _mexe     request.body, request.headers)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 1053, in request     self._send_request(method, url, body, headers)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 1093, in _send_request     self.endheaders(body)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 1049, in endheaders     self._send_output(message_body)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 893, in _send_output     self.send(msg)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 855, in send     self.connect()   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 1274, in connect     server_hostname=server_hostname)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py\", line 352, in wrap_socket     _context=self)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py\", line 579, in __init__     self.do_handshake()   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py\", line 816, in do_handshake     match_hostname(self.getpeercert(), self.server_hostname)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py\", line 271, in match_hostname     % (hostname, ', '.join(map(repr, dnsnames)))) CertificateError: hostname 'informes.nexio.cat.s3.amazonaws.com' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com' ",
      "received_at": "2015-12-18T10:41:06+01:00",
      "generated_at": "2015-12-18T10:41:08+01:00",
      "display_received_at": "Dec 18 10:41:06",
      "source_id": 111735203,
      "source_name": "localhost_test",
      "hostname": "localhost_test",
      "severity": "Error",
      "facility": "User"
    },
    {
      "id": "614442927728668673",
      "source_ip": "77.230.10.247",
      "program": "nexio_web",
      "message": "Internal Server Error: /reports/generate/ Traceback (most recent call last):   File \"/Library/Python/2.7/site-packages/django/core/handlers/base.py\", line 111, in get_response     response = wrapped_callback(request, *callback_args, **callback_kwargs)   File \"/Library/Python/2.7/site-packages/django/views/generic/base.py\", line 69, in view     return self.dispatch(request, *args, **kwargs)   File \"/Library/Python/2.7/site-packages/django/views/generic/base.py\", line 87, in dispatch     return handler(request, *args, **kwargs)   File \"/Users/IvanSoriano/PycharmProjects/nexioweb/reports/views.py\", line 222, in get     obj = pdf_creator.generate_pdfs(request.GET['toPDF'], request.session['username'], request.session['sessionid'], noncompliance, omit_amazon, ids_checks)   File \"/Users/IvanSoriano/PycharmProjects/nexioweb/utils/pdf_maker_cron/pdf_creator_report.py\", line 166, in generate_pdfs     buff, name = self.generate_pdf(username, session, noncompliance, omit_amazon, id_check)   File \"/Users/IvanSoriano/PycharmProjects/nexioweb/utils/pdf_maker_cron/pdf_creator_report.py\", line 176, in generate_pdf     pdf, name = self.get_pdf(id)   File \"/Users/IvanSoriano/PycharmProjects/nexioweb/utils/pdf_maker_cron/pdf_creator_report.py\", line 313, in get_pdf     bucket = con.get_bucket('informes.nexio.cat')   File \"/Library/Python/2.7/site-packages/boto/s3/connection.py\", line 502, in get_bucket     return self.head_bucket(bucket_name, headers=headers)   File \"/Library/Python/2.7/site-packages/boto/s3/connection.py\", line 521, in head_bucket     response = self.make_request('HEAD', bucket_name, headers=headers)   File \"/Library/Python/2.7/site-packages/boto/s3/connection.py\", line 664, in make_request     retry_handler=retry_handler   File \"/Library/Python/2.7/site-packages/boto/connection.py\", line 1071, in make_request     retry_handler=retry_handler)   File \"/Library/Python/2.7/site-packages/boto/connection.py\", line 943, in _mexe     request.body, request.headers)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 1053, in request     self._send_request(method, url, body, headers)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 1093, in _send_request     self.endheaders(body)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 1049, in endheaders     self._send_output(message_body)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 893, in _send_output     self.send(msg)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 855, in send     self.connect()   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 1274, in connect     server_hostname=server_hostname)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py\", line 352, in wrap_socket     _context=self)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py\", line 579, in __init__     self.do_handshake()   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py\", line 816, in do_handshake     match_hostname(self.getpeercert(), self.server_hostname)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py\", line 271, in match_hostname     % (hostname, ', '.join(map(repr, dnsnames)))) CertificateError: hostname 'informes.nexio.cat.s3.amazonaws.com' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com' ",
      "received_at": "2015-12-18T10:43:52+01:00",
      "generated_at": "2015-12-18T10:43:53+01:00",
      "display_received_at": "Dec 18 10:43:52",
      "source_id": 111735203,
      "source_name": "localhost_test",
      "hostname": "localhost_test",
      "severity": "Error",
      "facility": "User"
    },
    {
      "id": "614448848282365962",
      "source_ip": "77.230.10.247",
      "program": "nexio_web",
      "message": "Internal Server Error: /reports/generate/ Traceback (most recent call last):   File \"/Library/Python/2.7/site-packages/django/core/handlers/base.py\", line 111, in get_response     response = wrapped_callback(request, *callback_args, **callback_kwargs)   File \"/Library/Python/2.7/site-packages/django/views/generic/base.py\", line 69, in view     return self.dispatch(request, *args, **kwargs)   File \"/Library/Python/2.7/site-packages/django/views/generic/base.py\", line 87, in dispatch     return handler(request, *args, **kwargs)   File \"/Users/IvanSoriano/PycharmProjects/nexioweb/reports/views.py\", line 222, in get     obj = pdf_creator.generate_pdfs(request.GET['toPDF'], request.session['username'], request.session['sessionid'], noncompliance, omit_amazon, ids_checks)   File \"/Users/IvanSoriano/PycharmProjects/nexioweb/utils/pdf_maker_cron/pdf_creator_report.py\", line 166, in generate_pdfs     buff, name = self.generate_pdf(username, session, noncompliance, omit_amazon, id_check)   File \"/Users/IvanSoriano/PycharmProjects/nexioweb/utils/pdf_maker_cron/pdf_creator_report.py\", line 176, in generate_pdf     pdf, name = self.get_pdf(id)   File \"/Users/IvanSoriano/PycharmProjects/nexioweb/utils/pdf_maker_cron/pdf_creator_report.py\", line 313, in get_pdf     bucket = con.get_bucket('informes.nexio.cat')   File \"/Library/Python/2.7/site-packages/boto/s3/connection.py\", line 502, in get_bucket     return self.head_bucket(bucket_name, headers=headers)   File \"/Library/Python/2.7/site-packages/boto/s3/connection.py\", line 521, in head_bucket     response = self.make_request('HEAD', bucket_name, headers=headers)   File \"/Library/Python/2.7/site-packages/boto/s3/connection.py\", line 664, in make_request     retry_handler=retry_handler   File \"/Library/Python/2.7/site-packages/boto/connection.py\", line 1071, in make_request     retry_handler=retry_handler)   File \"/Library/Python/2.7/site-packages/boto/connection.py\", line 943, in _mexe     request.body, request.headers)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 1053, in request     self._send_request(method, url, body, headers)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 1093, in _send_request     self.endheaders(body)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 1049, in endheaders     self._send_output(message_body)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 893, in _send_output     self.send(msg)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 855, in send     self.connect()   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 1274, in connect     server_hostname=server_hostname)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py\", line 352, in wrap_socket     _context=self)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py\", line 579, in __init__     self.do_handshake()   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py\", line 816, in do_handshake     match_hostname(self.getpeercert(), self.server_hostname)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py\", line 271, in match_hostname     % (hostname, ', '.join(map(repr, dnsnames)))) CertificateError: hostname 'informes.nexio.cat.s3.amazonaws.com' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com' ",
      "received_at": "2015-12-18T11:07:23+01:00",
      "generated_at": "2015-12-18T11:07:25+01:00",
      "display_received_at": "Dec 18 11:07:23",
      "source_id": 111735203,
      "source_name": "localhost_test",
      "hostname": "localhost_test",
      "severity": "Error",
      "facility": "User"
    },
    {
      "id": "614449686589517824",
      "source_ip": "77.230.10.247",
      "program": "nexio_web",
      "message": "Internal Server Error: /reports/generate/ Traceback (most recent call last):   File \"/Library/Python/2.7/site-packages/django/core/handlers/base.py\", line 111, in get_response     response = wrapped_callback(request, *callback_args, **callback_kwargs)   File \"/Library/Python/2.7/site-packages/django/views/generic/base.py\", line 69, in view     return self.dispatch(request, *args, **kwargs)   File \"/Library/Python/2.7/site-packages/django/views/generic/base.py\", line 87, in dispatch     return handler(request, *args, **kwargs)   File \"/Users/IvanSoriano/PycharmProjects/nexioweb/reports/views.py\", line 222, in get     obj = pdf_creator.generate_pdfs(request.GET['toPDF'], request.session['username'], request.session['sessionid'], noncompliance, omit_amazon, ids_checks)   File \"/Users/IvanSoriano/PycharmProjects/nexioweb/utils/pdf_maker_cron/pdf_creator_report.py\", line 166, in generate_pdfs     buff, name = self.generate_pdf(username, session, noncompliance, omit_amazon, id_check)   File \"/Users/IvanSoriano/PycharmProjects/nexioweb/utils/pdf_maker_cron/pdf_creator_report.py\", line 176, in generate_pdf     pdf, name = self.get_pdf(id)   File \"/Users/IvanSoriano/PycharmProjects/nexioweb/utils/pdf_maker_cron/pdf_creator_report.py\", line 313, in get_pdf     bucket = con.get_bucket('informes.nexio.cat')   File \"/Library/Python/2.7/site-packages/boto/s3/connection.py\", line 502, in get_bucket     return self.head_bucket(bucket_name, headers=headers)   File \"/Library/Python/2.7/site-packages/boto/s3/connection.py\", line 521, in head_bucket     response = self.make_request('HEAD', bucket_name, headers=headers)   File \"/Library/Python/2.7/site-packages/boto/s3/connection.py\", line 664, in make_request     retry_handler=retry_handler   File \"/Library/Python/2.7/site-packages/boto/connection.py\", line 1071, in make_request     retry_handler=retry_handler)   File \"/Library/Python/2.7/site-packages/boto/connection.py\", line 943, in _mexe     request.body, request.headers)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 1053, in request     self._send_request(method, url, body, headers)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 1093, in _send_request     self.endheaders(body)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 1049, in endheaders     self._send_output(message_body)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 893, in _send_output     self.send(msg)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 855, in send     self.connect()   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 1274, in connect     server_hostname=server_hostname)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py\", line 352, in wrap_socket     _context=self)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py\", line 579, in __init__     self.do_handshake()   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py\", line 816, in do_handshake     match_hostname(self.getpeercert(), self.server_hostname)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py\", line 271, in match_hostname     % (hostname, ', '.join(map(repr, dnsnames)))) CertificateError: hostname 'informes.nexio.cat.s3.amazonaws.com' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com' ",
      "received_at": "2015-12-18T11:10:43+01:00",
      "generated_at": "2015-12-18T11:10:45+01:00",
      "display_received_at": "Dec 18 11:10:43",
      "source_id": 111735203,
      "source_name": "localhost_test",
      "hostname": "localhost_test",
      "severity": "Error",
      "facility": "User"
    },
    {
      "id": "614450063623892996",
      "source_ip": "77.230.10.247",
      "program": "nexio_web",
      "message": "Internal Server Error: /reports/generate/ Traceback (most recent call last):   File \"/Library/Python/2.7/site-packages/django/core/handlers/base.py\", line 111, in get_response     response = wrapped_callback(request, *callback_args, **callback_kwargs)   File \"/Library/Python/2.7/site-packages/django/views/generic/base.py\", line 69, in view     return self.dispatch(request, *args, **kwargs)   File \"/Library/Python/2.7/site-packages/django/views/generic/base.py\", line 87, in dispatch     return handler(request, *args, **kwargs)   File \"/Users/IvanSoriano/PycharmProjects/nexioweb/reports/views.py\", line 222, in get     obj = pdf_creator.generate_pdfs(request.GET['toPDF'], request.session['username'], request.session['sessionid'], noncompliance, omit_amazon, ids_checks)   File \"/Users/IvanSoriano/PycharmProjects/nexioweb/utils/pdf_maker_cron/pdf_creator_report.py\", line 166, in generate_pdfs     buff, name = self.generate_pdf(username, session, noncompliance, omit_amazon, id_check)   File \"/Users/IvanSoriano/PycharmProjects/nexioweb/utils/pdf_maker_cron/pdf_creator_report.py\", line 176, in generate_pdf     pdf, name = self.get_pdf(id)   File \"/Users/IvanSoriano/PycharmProjects/nexioweb/utils/pdf_maker_cron/pdf_creator_report.py\", line 313, in get_pdf     bucket = con.get_bucket('informes.nexio.cat')   File \"/Library/Python/2.7/site-packages/boto/s3/connection.py\", line 502, in get_bucket     return self.head_bucket(bucket_name, headers=headers)   File \"/Library/Python/2.7/site-packages/boto/s3/connection.py\", line 521, in head_bucket     response = self.make_request('HEAD', bucket_name, headers=headers)   File \"/Library/Python/2.7/site-packages/boto/s3/connection.py\", line 664, in make_request     retry_handler=retry_handler   File \"/Library/Python/2.7/site-packages/boto/connection.py\", line 1071, in make_request     retry_handler=retry_handler)   File \"/Library/Python/2.7/site-packages/boto/connection.py\", line 943, in _mexe     request.body, request.headers)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 1053, in request     self._send_request(method, url, body, headers)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 1093, in _send_request     self.endheaders(body)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 1049, in endheaders     self._send_output(message_body)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 893, in _send_output     self.send(msg)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 855, in send     self.connect()   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 1274, in connect     server_hostname=server_hostname)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py\", line 352, in wrap_socket     _context=self)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py\", line 579, in __init__     self.do_handshake()   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py\", line 816, in do_handshake     match_hostname(self.getpeercert(), self.server_hostname)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py\", line 271, in match_hostname     % (hostname, ', '.join(map(repr, dnsnames)))) CertificateError: hostname 'informes.nexio.cat.s3.amazonaws.com' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com' ",
      "received_at": "2015-12-18T11:12:13+01:00",
      "generated_at": "2015-12-18T11:12:15+01:00",
      "display_received_at": "Dec 18 11:12:13",
      "source_id": 111735203,
      "source_name": "localhost_test",
      "hostname": "localhost_test",
      "severity": "Error",
      "facility": "User"
    },
    {
      "id": "614459656605315072",
      "source_ip": "77.230.10.247",
      "program": "nexio_web",
      "message": "Internal Server Error: /reports/generate/ Traceback (most recent call last):   File \"/Library/Python/2.7/site-packages/django/core/handlers/base.py\", line 111, in get_response     response = wrapped_callback(request, *callback_args, **callback_kwargs)   File \"/Library/Python/2.7/site-packages/django/views/generic/base.py\", line 69, in view     return self.dispatch(request, *args, **kwargs)   File \"/Library/Python/2.7/site-packages/django/views/generic/base.py\", line 87, in dispatch     return handler(request, *args, **kwargs)   File \"/Users/IvanSoriano/PycharmProjects/nexioweb/reports/views.py\", line 222, in get     obj = pdf_creator.generate_pdfs(request.GET['toPDF'], request.session['username'], request.session['sessionid'], noncompliance, omit_amazon, ids_checks)   File \"/Users/IvanSoriano/PycharmProjects/nexioweb/utils/pdf_maker_cron/pdf_creator_report.py\", line 166, in generate_pdfs     buff, name = self.generate_pdf(username, session, noncompliance, omit_amazon, id_check)   File \"/Users/IvanSoriano/PycharmProjects/nexioweb/utils/pdf_maker_cron/pdf_creator_report.py\", line 176, in generate_pdf     pdf, name = self.get_pdf(id)   File \"/Users/IvanSoriano/PycharmProjects/nexioweb/utils/pdf_maker_cron/pdf_creator_report.py\", line 313, in get_pdf     bucket = con.get_bucket('informes.nexio.cat')   File \"/Library/Python/2.7/site-packages/boto/s3/connection.py\", line 502, in get_bucket     return self.head_bucket(bucket_name, headers=headers)   File \"/Library/Python/2.7/site-packages/boto/s3/connection.py\", line 521, in head_bucket     response = self.make_request('HEAD', bucket_name, headers=headers)   File \"/Library/Python/2.7/site-packages/boto/s3/connection.py\", line 664, in make_request     retry_handler=retry_handler   File \"/Library/Python/2.7/site-packages/boto/connection.py\", line 1071, in make_request     retry_handler=retry_handler)   File \"/Library/Python/2.7/site-packages/boto/connection.py\", line 943, in _mexe     request.body, request.headers)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 1053, in request     self._send_request(method, url, body, headers)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 1093, in _send_request     self.endheaders(body)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 1049, in endheaders     self._send_output(message_body)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 893, in _send_output     self.send(msg)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 855, in send     self.connect()   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 1274, in connect     server_hostname=server_hostname)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py\", line 352, in wrap_socket     _context=self)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py\", line 579, in __init__     self.do_handshake()   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py\", line 816, in do_handshake     match_hostname(self.getpeercert(), self.server_hostname)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py\", line 271, in match_hostname     % (hostname, ', '.join(map(repr, dnsnames)))) CertificateError: hostname 'informes.nexio.cat.s3.amazonaws.com' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com' ",
      "received_at": "2015-12-18T11:50:20+01:00",
      "generated_at": "2015-12-18T11:50:20+01:00",
      "display_received_at": "Dec 18 11:50:20",
      "source_id": 111735203,
      "source_name": "localhost_test",
      "hostname": "localhost_test",
      "severity": "Error",
      "facility": "User"
    },
    {
      "id": "614459707805184001",
      "source_ip": "77.230.10.247",
      "program": "nexio_web",
      "message": "Internal Server Error: /reports/generate/ Traceback (most recent call last):   File \"/Library/Python/2.7/site-packages/django/core/handlers/base.py\", line 111, in get_response     response = wrapped_callback(request, *callback_args, **callback_kwargs)   File \"/Library/Python/2.7/site-packages/django/views/generic/base.py\", line 69, in view     return self.dispatch(request, *args, **kwargs)   File \"/Library/Python/2.7/site-packages/django/views/generic/base.py\", line 87, in dispatch     return handler(request, *args, **kwargs)   File \"/Users/IvanSoriano/PycharmProjects/nexioweb/reports/views.py\", line 222, in get     obj = pdf_creator.generate_pdfs(request.GET['toPDF'], request.session['username'], request.session['sessionid'], noncompliance, omit_amazon, ids_checks)   File \"/Users/IvanSoriano/PycharmProjects/nexioweb/utils/pdf_maker_cron/pdf_creator_report.py\", line 166, in generate_pdfs     buff, name = self.generate_pdf(username, session, noncompliance, omit_amazon, id_check)   File \"/Users/IvanSoriano/PycharmProjects/nexioweb/utils/pdf_maker_cron/pdf_creator_report.py\", line 176, in generate_pdf     pdf, name = self.get_pdf(id)   File \"/Users/IvanSoriano/PycharmProjects/nexioweb/utils/pdf_maker_cron/pdf_creator_report.py\", line 313, in get_pdf     bucket = con.get_bucket('informes.nexio.cat')   File \"/Library/Python/2.7/site-packages/boto/s3/connection.py\", line 502, in get_bucket     return self.head_bucket(bucket_name, headers=headers)   File \"/Library/Python/2.7/site-packages/boto/s3/connection.py\", line 521, in head_bucket     response = self.make_request('HEAD', bucket_name, headers=headers)   File \"/Library/Python/2.7/site-packages/boto/s3/connection.py\", line 664, in make_request     retry_handler=retry_handler   File \"/Library/Python/2.7/site-packages/boto/connection.py\", line 1071, in make_request     retry_handler=retry_handler)   File \"/Library/Python/2.7/site-packages/boto/connection.py\", line 943, in _mexe     request.body, request.headers)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 1053, in request     self._send_request(method, url, body, headers)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 1093, in _send_request     self.endheaders(body)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 1049, in endheaders     self._send_output(message_body)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 893, in _send_output     self.send(msg)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 855, in send     self.connect()   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py\", line 1274, in connect     server_hostname=server_hostname)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py\", line 352, in wrap_socket     _context=self)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py\", line 579, in __init__     self.do_handshake()   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py\", line 816, in do_handshake     match_hostname(self.getpeercert(), self.server_hostname)   File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py\", line 271, in match_hostname     % (hostname, ', '.join(map(repr, dnsnames)))) CertificateError: hostname 'informes.nexio.cat.s3.amazonaws.com' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com' ",
      "received_at": "2015-12-18T11:50:32+01:00",
      "generated_at": "2015-12-18T11:50:32+01:00",
      "display_received_at": "Dec 18 11:50:32",
      "source_id": 111735203,
      "source_name": "localhost_test",
      "hostname": "localhost_test",
      "severity": "Error",
      "facility": "User"
    },
    {
      "id": "614461312034189321",
      "source_ip": "82.98.176.85",
      "program": "apache-error",
      "message": "[Fri Dec 18 10:56:55 2015] [error] [SERVER_RESULT] Server method returned: [{u'change_date': u'2015-10-19T09:45:43', u'data': u'Informe: -1', u'from': {u'fullName': u'Sistema Nexio', u'role': u'Sistema', u'name': u'Sistema'}, u'change_number': u'1', u'new_state': u'Oberta'}, {u'last_state': u'Oberta', u'from': {u'fullName': u'Gestor Demo', u'role': u'gestor', u'name': u'demogestor'}, u'new_state': u'Assignada', u'to': {u'fullName': u'Executor Demo', u'role': u'executor', u'name': u'demoexecutor'}, u'change_date': u'2015-10-28T12:00:46', u'data': u'', u'change_number': u'2'}, {u'last_state': u'Assignada', u'from': {u'fullName': u'Executor Demo', u'role': u'executor', u'name': u'demoexecutor'}, u'new_state': u'Pendent de resposta', u'to': {u'fullName': u'', u'role': u'client', u'name': u''}, u'change_date': u'2015-10-28T12:05:33', u'data': u'00:00:00', u'change_number': u'3'}, {u'last_state': u'Pendent de resposta', u'from': {u'fullName': u'Falck  Demo', u'role': u'client', u'name': u'demofalck'}, u'new_state'",
      "received_at": "2015-12-18T11:56:55+01:00",
      "generated_at": "2015-12-18T11:56:55+01:00",
      "display_received_at": "Dec 18 11:56:55",
      "source_id": 91453434,
      "source_name": "vls15613",
      "hostname": "vls15613",
      "severity": "Notice",
      "facility": "Local1"
    }
  ],
  "reached_beginning": true,
  "min_time_at": "2015-12-16T16:00:01-08:00"
}
